/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3SgxD942qJV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Label } from "@/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"

export function JokeComponent() {
  const [jokeType, setJokeType] = useState("witty")
  return (
    <div className="bg-background text-foreground min-h-screen flex flex-col items-center justify-center px-4 py-8">
      <div className="max-w-2xl w-full">
        <div className="mb-8 text-center">
          <h1 className="text-3xl font-bold">Joke Generator</h1>
          <p className="text-muted-foreground">Automatically generated jokes for your entertainment.</p>
        </div>
        <div className="grid gap-4">
          <div className="flex justify-between items-center">
            <div className="flex items-center gap-2">
              <Label htmlFor="joke-type" className="text-sm font-medium">
                Joke Tone:
              </Label>
              <Select id="joke-type" value={jokeType} onValueChange={setJokeType} className="w-[180px]">
                <SelectTrigger>
                  <SelectValue placeholder="Select tone" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="witty">Witty</SelectItem>
                  <SelectItem value="sarcastic">Sarcastic</SelectItem>
                  <SelectItem value="silly">Silly</SelectItem>
                  <SelectItem value="dark">Dark</SelectItem>
                  <SelectItem value="goofy">Goofy</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button onClick={() => {}}>Generate New Jokes</Button>
          </div>
          <Tabs defaultValue={jokeType} className="w-full">
            <TabsList className="grid grid-cols-5 w-full">
              <TabsTrigger value="witty">Witty</TabsTrigger>
              <TabsTrigger value="sarcastic">Sarcastic</TabsTrigger>
              <TabsTrigger value="silly">Silly</TabsTrigger>
              <TabsTrigger value="dark">Dark</TabsTrigger>
              <TabsTrigger value="goofy">Goofy</TabsTrigger>
            </TabsList>
            <TabsContent value="witty">
              <div className="grid gap-4">
                <Card>
                  <CardHeader>
                    <CardTitle>Why don't scientists trust atoms?</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p>Because they make up everything!</p>
                  </CardContent>
                  <CardFooter className="flex justify-end">
                    <Button variant="ghost" size="icon" onClick={() => {}}>
                      <ShareIcon className="h-4 w-4" />
                      <span className="sr-only">Share</span>
                    </Button>
                  </CardFooter>
                </Card>
              </div>
            </TabsContent>
            <TabsContent value="sarcastic">
              <div className="grid gap-4" />
            </TabsContent>
            <TabsContent value="silly">
              <div className="grid gap-4">
                <Card>
                  <CardHeader>
                    <CardTitle>Why can't a bicycle stand up by itself?</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p>It's two-tired!</p>
                  </CardContent>
                  <CardFooter className="flex justify-end">
                    <Button variant="ghost" size="icon" onClick={() => {}}>
                      <ShareIcon className="h-4 w-4" />
                      <span className="sr-only">Share</span>
                    </Button>
                  </CardFooter>
                </Card>
              </div>
            </TabsContent>
            <TabsContent value="dark">
              <div className="grid gap-4" />
            </TabsContent>
            <TabsContent value="goofy">
              <div className="grid gap-4">
                <Card>
                  <CardHeader>
                    <CardTitle>Why did the tomato turn red?</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p>Because it saw the salad dressing!</p>
                  </CardContent>
                  <CardFooter className="flex justify-end">
                    <Button variant="ghost" size="icon" onClick={() => {}}>
                      <ShareIcon className="h-4 w-4" />
                      <span className="sr-only">Share</span>
                    </Button>
                  </CardFooter>
                </Card>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </div>
  )
}

function ShareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>
  )
}
